--------------------------------------------------------
--  File created - niedziela-marca-09-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ABSENCJE
--------------------------------------------------------

  CREATE TABLE "SHOP"."ABSENCJE" 
   (	"ID" NUMBER, 
	"ID_PRACOWNIKA" NUMBER, 
	"PA_KOD" NUMBER, 
	"DATA_OD" DATE, 
	"DATA_DO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "SHOP"."DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE), 
	"MANAGER_ID" NUMBER, 
	"CITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS2
--------------------------------------------------------

  CREATE TABLE "SHOP"."DEPARTMENTS2" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE), 
	"MANAGER_ID" NUMBER, 
	"CITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "SHOP"."EMPLOYEES" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"LAST_NAME" VARCHAR2(60 BYTE), 
	"PRESONAL_ID" VARCHAR2(11 BYTE), 
	"KIND_OF_SEX" VARCHAR2(1 BYTE), 
	"BIRTH_DATE" DATE, 
	"MONEY" NUMBER, 
	"DEPARTMENT_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES_ARCHIVES
--------------------------------------------------------

  CREATE TABLE "SHOP"."EMPLOYEES_ARCHIVES" 
   (	"EVENT_DATE" DATE, 
	"EVENT_TYPE" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"OLD_ID" NUMBER, 
	"OLD_FIRST_NAME" VARCHAR2(30 BYTE), 
	"OLD_LAST_NAME" VARCHAR2(60 BYTE), 
	"OLD_PRESONAL_ID" VARCHAR2(11 BYTE), 
	"OLD_KIND_OF_SEX" VARCHAR2(1 BYTE), 
	"OLD_BIRTH_DATE" DATE, 
	"OLD_MONEY" NUMBER, 
	"OLD_DEPARTMENT_CODE" NUMBER, 
	"NEW_ID" NUMBER, 
	"NEW_FIRST_NAME" VARCHAR2(30 BYTE), 
	"NEW_LAST_NAME" VARCHAR2(60 BYTE), 
	"NEW_PRESONAL_ID" VARCHAR2(11 BYTE), 
	"NEW_KIND_OF_SEX" VARCHAR2(1 BYTE), 
	"NEW_BIRTH_DATE" DATE, 
	"NEW_MONEY" NUMBER, 
	"NEW_DEPARTMENT_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FAKTURY_SPRZEDAZY
--------------------------------------------------------

  CREATE TABLE "SHOP"."FAKTURY_SPRZEDAZY" 
   (	"ID_FAKTURY" NUMBER, 
	"DATA_FAKTURY" DATE, 
	"ID_KLIENTA" NUMBER, 
	"WARTOSC_NETTO" NUMBER, 
	"WARTOSC_BRUTTO" NUMBER, 
	"STAWKA_PODATKU" NUMBER, 
	"WALUTA" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEDNOSTKI_PRODUKTOW
--------------------------------------------------------

  CREATE TABLE "SHOP"."JEDNOSTKI_PRODUKTOW" 
   (	"ID" NUMBER, 
	"ID_PRODUKTU" NUMBER, 
	"JM" VARCHAR2(10 BYTE), 
	"JM_ALT" VARCHAR2(10 BYTE), 
	"PRZELICZNIK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "SHOP"."KLIENCI" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(30 BYTE), 
	"NAZWISKO" VARCHAR2(60 BYTE), 
	"PESEL" VARCHAR2(11 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(10 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SHOP"."PRODUCTS" 
   (	"ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"TYPE_OF_PRODUCT" VARCHAR2(30 BYTE), 
	"PRICE_SELL" NUMBER, 
	"PRICE_BUY" NUMBER, 
	"VAT" NUMBER, 
	"JM" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRZYCZYNY_ABSENCJI
--------------------------------------------------------

  CREATE TABLE "SHOP"."PRZYCZYNY_ABSENCJI" 
   (	"ID" NUMBER, 
	"NAZWA" VARCHAR2(200 BYTE), 
	"CZY_ZGODA" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"UWAGI" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RODZAJE_PRODUKTOW
--------------------------------------------------------

  CREATE TABLE "SHOP"."RODZAJE_PRODUKTOW" 
   (	"KOD" VARCHAR2(10 BYTE), 
	"NAZWA" VARCHAR2(50 BYTE), 
	"WYMAGANA_KONCESJA" CHAR(1 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "EXTERNAL_TABLES_DIR4"
      ACCESS PARAMETERS
      ( FIELDS TERMINATED BY ';'
)
      LOCATION
       ( 'product_type.csv'
       )
    )
   REJECT LIMIT 0 ;
--------------------------------------------------------
--  DDL for Table RODZAJE_SRODKOW_TRANSPORTU
--------------------------------------------------------

  CREATE TABLE "SHOP"."RODZAJE_SRODKOW_TRANSPORTU" 
   (	"KOD" VARCHAR2(10 BYTE), 
	"PELNA_NAZWA" VARCHAR2(80 BYTE), 
	"MIN_DLUGOSC" NUMBER, 
	"MAX_DLUGOSC" NUMBER, 
	"MIN_WAGA" NUMBER, 
	"MAX_WAGA" NUMBER, 
	"LADOWNOSC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "SHOP"."SUPPLIERS" 
   (	"ID_SUPPLIER" NUMBER, 
	"NAME_SUPPLIER" VARCHAR2(50 BYTE), 
	"TYPE_CODE_TRANSPORT" VARCHAR2(10 BYTE), 
	"ACTIVITY_STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPE_OF_PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SHOP"."TYPE_OF_PRODUCTS" 
   (	"TYPE_OF_PRODUCT" VARCHAR2(20 BYTE), 
	"FULL_NAME_PRODUCT" VARCHAR2(40 BYTE), 
	"DISCOUNT" NUMBER, 
	"EXPIRATION_DATE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAKUPY
--------------------------------------------------------

  CREATE TABLE "SHOP"."ZAKUPY" 
   (	"ID_ZAKUPU" NUMBER, 
	"ID_KLIENTA" NUMBER, 
	"CZY_PARAGON" VARCHAR2(1 BYTE), 
	"CZY_FAKTURA" VARCHAR2(1 BYTE), 
	"ID_FAKTURY" NUMBER, 
	"DATA_ZAKUPU" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAKUPY_POZYCJE
--------------------------------------------------------

  CREATE TABLE "SHOP"."ZAKUPY_POZYCJE" 
   (	"ID_ZAKUPU" NUMBER, 
	"NUMER_POZYCJI" NUMBER, 
	"ID_PRODUKTU" NUMBER, 
	"ILOSC" NUMBER, 
	"CZY_REKLAMACJA" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SHOP.ABSENCJE
SET DEFINE OFF;
Insert into SHOP.ABSENCJE (ID,ID_PRACOWNIKA,PA_KOD,DATA_OD,DATA_DO) values ('1','11','2',to_date('18/09/04','RR/MM/DD'),to_date('19/03/04','RR/MM/DD'));
Insert into SHOP.ABSENCJE (ID,ID_PRACOWNIKA,PA_KOD,DATA_OD,DATA_DO) values ('2','5','1',to_date('17/08/12','RR/MM/DD'),to_date('18/05/04','RR/MM/DD'));
Insert into SHOP.ABSENCJE (ID,ID_PRACOWNIKA,PA_KOD,DATA_OD,DATA_DO) values ('3','15','4',to_date('18/01/15','RR/MM/DD'),to_date('18/01/27','RR/MM/DD'));
Insert into SHOP.ABSENCJE (ID,ID_PRACOWNIKA,PA_KOD,DATA_OD,DATA_DO) values ('4','18','4',to_date('18/02/27','RR/MM/DD'),to_date('18/03/05','RR/MM/DD'));
Insert into SHOP.ABSENCJE (ID,ID_PRACOWNIKA,PA_KOD,DATA_OD,DATA_DO) values ('5','15','9',to_date('18/10/05','RR/MM/DD'),to_date('18/10/05','RR/MM/DD'));
REM INSERTING into SHOP.DEPARTMENTS
SET DEFINE OFF;
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('1','księgowość','2','Warszawa Śródmieście');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('2','produkcja','11','Piaseczno');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('3','administracja','4','Warszawa Centrum');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('4','IT','3','Warszawa Centrum');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('5','Sprzedaż','5','Warszawa Śródmieście');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('6','planowanie i zakupy','5','Warszawa Ochota');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('7','hr','1','Kraków');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('12','logistyka','6','Zakopane');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('8','badanie i rozwój','12','Łodź');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('9','dział prawny','18','Szczecin');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('10','public relations','20','Gdańsk Oliwa');
Insert into SHOP.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('11','transport','19','Poznań');
REM INSERTING into SHOP.DEPARTMENTS2
SET DEFINE OFF;
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('1','księgowość','2','Warszawa Śródmieście');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('2','produkcja','11','Piaseczno');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('3','administracja','4','Warszawa Centrum');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('4','IT','3','Warszawa Centrum');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('5','Sprzedaż','5','Warszawa Śródmieście');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('6','planowanie i zakupy','5','Warszawa Ochota');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('7','hr','1','Kraków');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('12','logistyka','6','Zakopane');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('8','badanie i rozwój','12','Łodź');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('9','dział prawny','18','Szczecin');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('10','public relations','20','Gdańsk Oliwa');
Insert into SHOP.DEPARTMENTS2 (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,CITY) values ('11','transport','19','Poznań');
REM INSERTING into SHOP.EMPLOYEES
SET DEFINE OFF;
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('21','Sylwia','Dudek','88102018345','K',to_date('88/10/20','RR/MM/DD'),'7500','4');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('22','maciek','koto','52171313842','M',to_date('00/07/13','RR/MM/DD'),'5000','10');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('11','Sebastian','Krawczyk','88031269123','M',to_date('88/03/12','RR/MM/DD'),'7000','2');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('12','Jacek','Grzyma�a','80020366584','M',to_date('80/02/03','RR/MM/DD'),'7000','2');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('13','Pawe��','Kiepski','81121225836','M',to_date('81/12/12','RR/MM/DD'),'3500','5');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('14','Julia','�wi�ka�a','92101548732','K',to_date('92/10/15','RR/MM/DD'),'2300','5');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('15','Katarzyna','Zebra','98110843128','K',to_date('98/11/08','RR/MM/DD'),'7000','3');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('16','Przemys�aw','Grzyma�a','80020314725','M',to_date('80/02/03','RR/MM/DD'),'9000','12');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('17','Zofia','Pryk','91041516589','K',to_date('91/04/15','RR/MM/DD'),'4600','1');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('18','Paulina','Polak','65020761975','K',to_date('65/02/07','RR/MM/DD'),'3540','11');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('19','Robert','Polewicz','58090414763','M',to_date('58/09/04','RR/MM/DD'),'6500','9');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('20','J�zef','Wo�ecki','00071313842','M',to_date('00/07/13','RR/MM/DD'),'2900','9');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('2','Krzysztof','Kapusta','70122012345','M',to_date('70/12/20','RR/MM/DD'),'2500','1');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('3','Magdalena','Dzwonkowska','92081612345','K',to_date('92/08/16','RR/MM/DD'),'5000','4');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('4','Karol','Krawczyk','82010112345','M',to_date('82/01/01','RR/MM/DD'),'3000','3');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('5','Joanna','Bak','90121212345','K',to_date('90/12/12','RR/MM/DD'),'2700','6');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('6','Robert','Psikuta','95070815642','M',to_date('95/07/08','RR/MM/DD'),'4200','11');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('7','Stefan','Siarzewski','60051274391','M',to_date('60/05/12','RR/MM/DD'),'4550','10');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('8','Zofia','Brzydal','84021659712','K',to_date('84/02/16','RR/MM/DD'),'2400','9');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('9','Julia','Niedziela','81050242315','K',to_date('81/05/02','RR/MM/DD'),'7000','8');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('10','Bartosz','Karmel','58031245679','M',to_date('58/03/12','RR/MM/DD'),'5120','7');
Insert into SHOP.EMPLOYEES (ID,FIRST_NAME,LAST_NAME,PRESONAL_ID,KIND_OF_SEX,BIRTH_DATE,MONEY,DEPARTMENT_CODE) values ('1','Jan','Kowalski','88020512345','M',to_date('88/02/05','RR/MM/DD'),'4000','12');
REM INSERTING into SHOP.EMPLOYEES_ARCHIVES
SET DEFINE OFF;
Insert into SHOP.EMPLOYEES_ARCHIVES (EVENT_DATE,EVENT_TYPE,USER_NAME,OLD_ID,OLD_FIRST_NAME,OLD_LAST_NAME,OLD_PRESONAL_ID,OLD_KIND_OF_SEX,OLD_BIRTH_DATE,OLD_MONEY,OLD_DEPARTMENT_CODE,NEW_ID,NEW_FIRST_NAME,NEW_LAST_NAME,NEW_PRESONAL_ID,NEW_KIND_OF_SEX,NEW_BIRTH_DATE,NEW_MONEY,NEW_DEPARTMENT_CODE) values (to_date('25/03/06','RR/MM/DD'),'INSERT','SHOP','25','Roman','Kowalski','90020136989','M',to_date('90/02/01','RR/MM/DD'),'5000','1',null,null,null,null,null,null,null,null);
Insert into SHOP.EMPLOYEES_ARCHIVES (EVENT_DATE,EVENT_TYPE,USER_NAME,OLD_ID,OLD_FIRST_NAME,OLD_LAST_NAME,OLD_PRESONAL_ID,OLD_KIND_OF_SEX,OLD_BIRTH_DATE,OLD_MONEY,OLD_DEPARTMENT_CODE,NEW_ID,NEW_FIRST_NAME,NEW_LAST_NAME,NEW_PRESONAL_ID,NEW_KIND_OF_SEX,NEW_BIRTH_DATE,NEW_MONEY,NEW_DEPARTMENT_CODE) values (to_date('25/03/06','RR/MM/DD'),'INSERT','SHOP',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SHOP.EMPLOYEES_ARCHIVES (EVENT_DATE,EVENT_TYPE,USER_NAME,OLD_ID,OLD_FIRST_NAME,OLD_LAST_NAME,OLD_PRESONAL_ID,OLD_KIND_OF_SEX,OLD_BIRTH_DATE,OLD_MONEY,OLD_DEPARTMENT_CODE,NEW_ID,NEW_FIRST_NAME,NEW_LAST_NAME,NEW_PRESONAL_ID,NEW_KIND_OF_SEX,NEW_BIRTH_DATE,NEW_MONEY,NEW_DEPARTMENT_CODE) values (to_date('25/03/06','RR/MM/DD'),'DELETE','SHOP','24','Roman','Kowalski','90020136989','M',to_date('90/02/01','RR/MM/DD'),'5000','1',null,null,null,null,null,null,null,null);
Insert into SHOP.EMPLOYEES_ARCHIVES (EVENT_DATE,EVENT_TYPE,USER_NAME,OLD_ID,OLD_FIRST_NAME,OLD_LAST_NAME,OLD_PRESONAL_ID,OLD_KIND_OF_SEX,OLD_BIRTH_DATE,OLD_MONEY,OLD_DEPARTMENT_CODE,NEW_ID,NEW_FIRST_NAME,NEW_LAST_NAME,NEW_PRESONAL_ID,NEW_KIND_OF_SEX,NEW_BIRTH_DATE,NEW_MONEY,NEW_DEPARTMENT_CODE) values (to_date('25/03/06','RR/MM/DD'),'INSERT','SHOP',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SHOP.EMPLOYEES_ARCHIVES (EVENT_DATE,EVENT_TYPE,USER_NAME,OLD_ID,OLD_FIRST_NAME,OLD_LAST_NAME,OLD_PRESONAL_ID,OLD_KIND_OF_SEX,OLD_BIRTH_DATE,OLD_MONEY,OLD_DEPARTMENT_CODE,NEW_ID,NEW_FIRST_NAME,NEW_LAST_NAME,NEW_PRESONAL_ID,NEW_KIND_OF_SEX,NEW_BIRTH_DATE,NEW_MONEY,NEW_DEPARTMENT_CODE) values (to_date('25/03/06','RR/MM/DD'),'DELETE','SHOP','23','Roman','Kowalski','90020136989','M',to_date('90/02/01','RR/MM/DD'),'4000','1',null,null,null,null,null,null,null,null);
Insert into SHOP.EMPLOYEES_ARCHIVES (EVENT_DATE,EVENT_TYPE,USER_NAME,OLD_ID,OLD_FIRST_NAME,OLD_LAST_NAME,OLD_PRESONAL_ID,OLD_KIND_OF_SEX,OLD_BIRTH_DATE,OLD_MONEY,OLD_DEPARTMENT_CODE,NEW_ID,NEW_FIRST_NAME,NEW_LAST_NAME,NEW_PRESONAL_ID,NEW_KIND_OF_SEX,NEW_BIRTH_DATE,NEW_MONEY,NEW_DEPARTMENT_CODE) values (to_date('25/03/06','RR/MM/DD'),'INSERT','SHOP',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into SHOP.FAKTURY_SPRZEDAZY
SET DEFINE OFF;
Insert into SHOP.FAKTURY_SPRZEDAZY (ID_FAKTURY,DATA_FAKTURY,ID_KLIENTA,WARTOSC_NETTO,WARTOSC_BRUTTO,STAWKA_PODATKU,WALUTA) values ('1',to_date('18/11/25','RR/MM/DD'),'5','25','30,75','23','PLN');
REM INSERTING into SHOP.JEDNOSTKI_PRODUKTOW
SET DEFINE OFF;
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('1','1','szt','kg','0,2');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('2','2','szt','kg','0,6');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('3','3','kg','szt','2');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('4','4','kg','szt','1');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('5','5','szt','l','1,5');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('6','5','szt','kg','1,6');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('7','6','szt','l','0,2');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('8','7','szt','l','1,5');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('9','8','szt','l','1,5');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('10','9','szt','l','2');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('11','10','szt','kg','0,05');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('12','11','szt','kg','0,08');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('13','12','szt','l','0,5');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('14','12','szt','kg','0,6');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('15','13','szt','kg','0,3');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('16','13','szt','l','0,25');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('17','14','szt','l','0,07');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('18','15','szt','l','0,5');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('19','16','szt','l','0,5');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('20','17','szt','l','0,7');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('21','18','szt','kg','0,35');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('22','19','szt','kg','1');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('23','20','szt','kg','1');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('24','21','kg','szt','5');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('25','22','kg','szt','4');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('26','23','kg','szt','6');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('27','24','kg','szt','8');
Insert into SHOP.JEDNOSTKI_PRODUKTOW (ID,ID_PRODUKTU,JM,JM_ALT,PRZELICZNIK) values ('28','25','kg','szt','7');
REM INSERTING into SHOP.KLIENCI
SET DEFINE OFF;
Insert into SHOP.KLIENCI (ID,IMIE,NAZWISKO,PESEL,KOD_POCZTOWY,MIEJSCOWOSC) values ('1','Bronis�aw','Foka','72120573948','09-400','P�ock');
Insert into SHOP.KLIENCI (ID,IMIE,NAZWISKO,PESEL,KOD_POCZTOWY,MIEJSCOWOSC) values ('2','Joanna','Fr�czak','80041146587','09-400','P�ock');
Insert into SHOP.KLIENCI (ID,IMIE,NAZWISKO,PESEL,KOD_POCZTOWY,MIEJSCOWOSC) values ('3','Kazimiera','Wec�aw','65091047612','22-100','Gda�sk');
Insert into SHOP.KLIENCI (ID,IMIE,NAZWISKO,PESEL,KOD_POCZTOWY,MIEJSCOWOSC) values ('4','Bartosz','Przybylski','01101442863','02-241','Warszawa');
Insert into SHOP.KLIENCI (ID,IMIE,NAZWISKO,PESEL,KOD_POCZTOWY,MIEJSCOWOSC) values ('5','Katarzyna','Fackiewicz','85031856317','30-006','Krak�w');
Insert into SHOP.KLIENCI (ID,IMIE,NAZWISKO,PESEL,KOD_POCZTOWY,MIEJSCOWOSC) values ('6','Krzysztof','Jarzyna','75110621863','70-003','Szczecin');
REM INSERTING into SHOP.PRODUCTS
SET DEFINE OFF;
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('1','Baton "Mars"','SLO','2,5','1,5','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('2','chleb','PIE','3','1,2','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('3','płatki owsiane 0.5kg','NAS','2,25','1,45','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('4','płatki owsiane 1kg','NAS','4','2,4','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('5','mleko','NAB','3,5','2','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('6','jogurt "Danone"','NAB','3,5','2','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('7','woda gazowana','NAP','1,9','1','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('8','woda niegazowana','NAP','1,9','1','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('9','oranżada','NAP','2,49','2','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('10','bułka pszenna','PIE','0,5','0,3','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('11','bułka żytnia','PIE','0,7','0,5','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('12','balsam do ciała','KOS','20','14','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('13','krem do rąk','KOS','8','6,4','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('14','dezodorant','KOS','9','4,4','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('15','piwo','ALK','4','2,8','30','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('16','wódka polska','ALK','25','14','30','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('17','whiskey','ALK','60','40','30','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('18','czekolada','SLO','5','2','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('19','ryż','NAS','3','1,5','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('20','kasza gryczana','NAS','3','1,7','23','szt');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('21','jabłko','OWO','4','2,52','16','kg');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('22','pomarańcza','OWO','8','5,01','16','kg');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('23','banan','OWO','7,25','4,99','16','kg');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('24','pomidor malinowy','WAR','12,99','10,99','23','kg');
Insert into SHOP.PRODUCTS (ID,PRODUCT_NAME,TYPE_OF_PRODUCT,PRICE_SELL,PRICE_BUY,VAT,JM) values ('25','OGÓREK','WAR','2,99','1,99','23','kg');
REM INSERTING into SHOP.PRZYCZYNY_ABSENCJI
SET DEFINE OFF;
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('1','urlop macierzyżski','N',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('2','urlop ojcowski','N',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('3','urlop rodzicielski','N',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('4','urlop wypoczynkowy','T',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('5','urlop wychowawczy','N',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('6','urlop szkoleniowy','T',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('7','urlop okolicznościowy','T',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('8','urlop bezpłatny','T',null);
Insert into SHOP.PRZYCZYNY_ABSENCJI (ID,NAZWA,CZY_ZGODA,UWAGI) values ('9','na żądanie','N',null);
REM INSERTING into SHOP.RODZAJE_PRODUKTOW
SET DEFINE OFF;
REM INSERTING into SHOP.RODZAJE_SRODKOW_TRANSPORTU
SET DEFINE OFF;
Insert into SHOP.RODZAJE_SRODKOW_TRANSPORTU (KOD,PELNA_NAZWA,MIN_DLUGOSC,MAX_DLUGOSC,MIN_WAGA,MAX_WAGA,LADOWNOSC) values ('VAN','van','3,5','4','1800','2400','1000');
Insert into SHOP.RODZAJE_SRODKOW_TRANSPORTU (KOD,PELNA_NAZWA,MIN_DLUGOSC,MAX_DLUGOSC,MIN_WAGA,MAX_WAGA,LADOWNOSC) values ('BUS','bus','3,8','4,2','1950','2800','1200');
Insert into SHOP.RODZAJE_SRODKOW_TRANSPORTU (KOD,PELNA_NAZWA,MIN_DLUGOSC,MAX_DLUGOSC,MIN_WAGA,MAX_WAGA,LADOWNOSC) values ('AUT','auto osobowe','2','3,2','800','1400','600');
Insert into SHOP.RODZAJE_SRODKOW_TRANSPORTU (KOD,PELNA_NAZWA,MIN_DLUGOSC,MAX_DLUGOSC,MIN_WAGA,MAX_WAGA,LADOWNOSC) values ('TIR','tir','12','20','5000','10000','30000');
Insert into SHOP.RODZAJE_SRODKOW_TRANSPORTU (KOD,PELNA_NAZWA,MIN_DLUGOSC,MAX_DLUGOSC,MIN_WAGA,MAX_WAGA,LADOWNOSC) values ('SKUT','skuter','1,65','2,24','300','500','200');
REM INSERTING into SHOP.SUPPLIERS
SET DEFINE OFF;
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('1','Morliny','VAN','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('2','Koral','BUS','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('3','Pepco','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('4','Lidl','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('5','Obi','VAN','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('6','Decathlon','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('7','Biedronka','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('8','Auchan','BUS','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('9','Lewiatan','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('10','Intermarche','VAN','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('11','Bricomarche','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('12','Tesco','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('13','E.Leclerc','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('14','Amica','BUS','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('15','Avon','AUT','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('16','Puma','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('17','Lego','VAN','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('18','Militaria','TIR','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('19','Delikatesy','AUT','A');
Insert into SHOP.SUPPLIERS (ID_SUPPLIER,NAME_SUPPLIER,TYPE_CODE_TRANSPORT,ACTIVITY_STATUS) values ('20','Jogobella','VAN','A');
REM INSERTING into SHOP.TYPE_OF_PRODUCTS
SET DEFINE OFF;
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('SLO','słodycz',null,'D');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('PIE','pieczywo',null,'K');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('NAS','nasiona',null,'D');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('NAB','nabiał',null,'K');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('NAP','napoje',null,'D');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('KOS','kosmetyki',null,'D');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('ALK','alkohol',null,'D');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('OWO','owoc',null,'K');
Insert into SHOP.TYPE_OF_PRODUCTS (TYPE_OF_PRODUCT,FULL_NAME_PRODUCT,DISCOUNT,EXPIRATION_DATE) values ('WAR','warzywo',null,'K');
REM INSERTING into SHOP.ZAKUPY
SET DEFINE OFF;
Insert into SHOP.ZAKUPY (ID_ZAKUPU,ID_KLIENTA,CZY_PARAGON,CZY_FAKTURA,ID_FAKTURY,DATA_ZAKUPU) values ('1','4','N','T','1',to_date('18/02/04','RR/MM/DD'));
Insert into SHOP.ZAKUPY (ID_ZAKUPU,ID_KLIENTA,CZY_PARAGON,CZY_FAKTURA,ID_FAKTURY,DATA_ZAKUPU) values ('2','2','T','N',null,to_date('18/09/04','RR/MM/DD'));
Insert into SHOP.ZAKUPY (ID_ZAKUPU,ID_KLIENTA,CZY_PARAGON,CZY_FAKTURA,ID_FAKTURY,DATA_ZAKUPU) values ('3','6','T','N',null,to_date('18/12/04','RR/MM/DD'));
REM INSERTING into SHOP.ZAKUPY_POZYCJE
SET DEFINE OFF;
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('1','1','25','0,5','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('1','2','20','1','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('1','3','5','10','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('1','4','8','8','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('1','5','7','5','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('2','1','9','2','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('3','1','1','1','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('3','2','17','7','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('3','3','22','12','N');
Insert into SHOP.ZAKUPY_POZYCJE (ID_ZAKUPU,NUMER_POZYCJI,ID_PRODUKTU,ILOSC,CZY_REKLAMACJA) values ('3','4','7','6','N');
--------------------------------------------------------
--  DDL for Index DEPARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."DEPARTMENTS_PK" ON "SHOP"."DEPARTMENTS" ("DEPARTMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPOLYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."EMPOLYEES_PK" ON "SHOP"."EMPLOYEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."PRODUCTS_PK" ON "SHOP"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008233
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008233" ON "SHOP"."TYPE_OF_PRODUCTS" ("TYPE_OF_PRODUCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008236
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008236" ON "SHOP"."SUPPLIERS" ("ID_SUPPLIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008238
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008238" ON "SHOP"."RODZAJE_SRODKOW_TRANSPORTU" ("KOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008242
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008242" ON "SHOP"."PRZYCZYNY_ABSENCJI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008243
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008243" ON "SHOP"."ABSENCJE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008248
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008248" ON "SHOP"."KLIENCI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008249
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008249" ON "SHOP"."FAKTURY_SPRZEDAZY" ("ID_FAKTURY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008251
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008251" ON "SHOP"."ZAKUPY" ("ID_ZAKUPU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008254
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008254" ON "SHOP"."ZAKUPY_POZYCJE" ("ID_ZAKUPU", "NUMER_POZYCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008257
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008257" ON "SHOP"."JEDNOSTKI_PRODUKTOW" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008243
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008243" ON "SHOP"."ABSENCJE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."DEPARTMENTS_PK" ON "SHOP"."DEPARTMENTS" ("DEPARTMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPOLYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."EMPOLYEES_PK" ON "SHOP"."EMPLOYEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008249
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008249" ON "SHOP"."FAKTURY_SPRZEDAZY" ("ID_FAKTURY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008257
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008257" ON "SHOP"."JEDNOSTKI_PRODUKTOW" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008248
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008248" ON "SHOP"."KLIENCI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."PRODUCTS_PK" ON "SHOP"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008242
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008242" ON "SHOP"."PRZYCZYNY_ABSENCJI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008238
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008238" ON "SHOP"."RODZAJE_SRODKOW_TRANSPORTU" ("KOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008236
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008236" ON "SHOP"."SUPPLIERS" ("ID_SUPPLIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008233
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008233" ON "SHOP"."TYPE_OF_PRODUCTS" ("TYPE_OF_PRODUCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008251
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008251" ON "SHOP"."ZAKUPY" ("ID_ZAKUPU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008254
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHOP"."SYS_C008254" ON "SHOP"."ZAKUPY_POZYCJE" ("ID_ZAKUPU", "NUMER_POZYCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AUID_EMPLOYEES_ARCHIVES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES" 
AFTER INSERT OR UPDATE OR DELETE
ON employees
FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO employees_archives
   ( 
         EVENT_DATE			
        ,EVENT_TYPE			
        ,USER_NAME			
        ,OLD_ID 			
        ,OLD_FIRST_NAME 	
        ,OLD_LAST_NAME 		
        ,OLD_PRESONAL_ID 	
        ,OLD_KIND_OF_SEX 	
        ,OLD_BIRTH_DATE 	
        ,OLD_MONEY 			
        ,OLD_DEPARTMENT_CODE
        ,NEW_ID 			
        ,NEW_FIRST_NAME 	
        ,NEW_LAST_NAME 		
        ,NEW_PRESONAL_ID 	
        ,NEW_KIND_OF_SEX 	
        ,NEW_BIRTH_DATE 	
        ,NEW_MONEY 			
        ,NEW_DEPARTMENT_CODE
)
   VALUES
   (
        SYSDATE
        , 'INSERT'
        , USER
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , :NEW.ID
        , :NEW.FIRST_NAME 
        , :NEW.LAST_NAME 
        , :NEW.PRESONAL_ID
        , :NEW.KIND_OF_SEX
        , :NEW.BIRTH_DATE
        , :NEW.MONEY
        , :NEW.DEPARTMENT_CODE
   );
END;

/
ALTER TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUID_EMPLOYEES_ARCHIVES2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES2" 
AFTER INSERT OR UPDATE OR DELETE
ON employees
FOR EACH ROW
DECLARE
BEGIN
    IF inserting THEN
            INSERT INTO employees_archives
               ( 
                     EVENT_DATE			
                    ,EVENT_TYPE			
                    ,USER_NAME			
                    ,OLD_ID 			
                    ,OLD_FIRST_NAME 	
                    ,OLD_LAST_NAME 		
                    ,OLD_PRESONAL_ID 	
                    ,OLD_KIND_OF_SEX 	
                    ,OLD_BIRTH_DATE 	
                    ,OLD_MONEY 			
                    ,OLD_DEPARTMENT_CODE
                    ,NEW_ID 			
                    ,NEW_FIRST_NAME 	
                    ,NEW_LAST_NAME 		
                    ,NEW_PRESONAL_ID 	
                    ,NEW_KIND_OF_SEX 	
                    ,NEW_BIRTH_DATE 	
                    ,NEW_MONEY 			
                    ,NEW_DEPARTMENT_CODE
            )
               VALUES
               (
                    SYSDATE
                    , 'INSERT'
                    , USER
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , :NEW.ID
                    , :NEW.FIRST_NAME 
                    , :NEW.LAST_NAME 
                    , :NEW.PRESONAL_ID
                    , :NEW.KIND_OF_SEX
                    , :NEW.BIRTH_DATE
                    , :NEW.MONEY
                    , :NEW.DEPARTMENT_CODE
               );
    ELSIF updating THEN
            INSERT INTO employees_archives
               ( 
                     EVENT_DATE			
                    ,EVENT_TYPE			
                    ,USER_NAME			
                    ,OLD_ID 			
                    ,OLD_FIRST_NAME 	
                    ,OLD_LAST_NAME 		
                    ,OLD_PRESONAL_ID 	
                    ,OLD_KIND_OF_SEX 	
                    ,OLD_BIRTH_DATE 	
                    ,OLD_MONEY 			
                    ,OLD_DEPARTMENT_CODE
                    ,NEW_ID 			
                    ,NEW_FIRST_NAME 	
                    ,NEW_LAST_NAME 		
                    ,NEW_PRESONAL_ID 	
                    ,NEW_KIND_OF_SEX 	
                    ,NEW_BIRTH_DATE 	
                    ,NEW_MONEY 			
                    ,NEW_DEPARTMENT_CODE
            )
               VALUES
               (
                    SYSDATE
                    , 'UPDATE'
                    , USER
                    , :OLD.ID
                    , :OLD.FIRST_NAME 
                    , :OLD.LAST_NAME 
                    , :OLD.PRESONAL_ID
                    , :OLD.KIND_OF_SEX
                    , :OLD.BIRTH_DATE
                    , :OLD.MONEY
                    , :OLD.DEPARTMENT_CODE
                    , :NEW.ID
                    , :NEW.FIRST_NAME 
                    , :NEW.LAST_NAME 
                    , :NEW.PRESONAL_ID
                    , :NEW.KIND_OF_SEX
                    , :NEW.BIRTH_DATE
                    , :NEW.MONEY
                    , :NEW.DEPARTMENT_CODE
               );
    ELSE 

                INSERT INTO employees_archives
               ( 
                     EVENT_DATE			
                    ,EVENT_TYPE			
                    ,USER_NAME			
                    ,OLD_ID 			
                    ,OLD_FIRST_NAME 	
                    ,OLD_LAST_NAME 		
                    ,OLD_PRESONAL_ID 	
                    ,OLD_KIND_OF_SEX 	
                    ,OLD_BIRTH_DATE 	
                    ,OLD_MONEY 			
                    ,OLD_DEPARTMENT_CODE
                    ,NEW_ID 			
                    ,NEW_FIRST_NAME 	
                    ,NEW_LAST_NAME 		
                    ,NEW_PRESONAL_ID 	
                    ,NEW_KIND_OF_SEX 	
                    ,NEW_BIRTH_DATE 	
                    ,NEW_MONEY 			
                    ,NEW_DEPARTMENT_CODE
            )
               VALUES
               (
                    SYSDATE
                    , 'DELETE'
                    , USER
                    , :OLD.ID
                    , :OLD.FIRST_NAME 
                    , :OLD.LAST_NAME 
                    , :OLD.PRESONAL_ID
                    , :OLD.KIND_OF_SEX
                    , :OLD.BIRTH_DATE
                    , :OLD.MONEY
                    , :OLD.DEPARTMENT_CODE
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
               );

    END IF;
END;

/
ALTER TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUID_EMPLOYEES_ARCHIVES2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES2" 
AFTER INSERT OR UPDATE OR DELETE
ON employees
FOR EACH ROW
DECLARE
BEGIN
    IF inserting THEN
            INSERT INTO employees_archives
               ( 
                     EVENT_DATE			
                    ,EVENT_TYPE			
                    ,USER_NAME			
                    ,OLD_ID 			
                    ,OLD_FIRST_NAME 	
                    ,OLD_LAST_NAME 		
                    ,OLD_PRESONAL_ID 	
                    ,OLD_KIND_OF_SEX 	
                    ,OLD_BIRTH_DATE 	
                    ,OLD_MONEY 			
                    ,OLD_DEPARTMENT_CODE
                    ,NEW_ID 			
                    ,NEW_FIRST_NAME 	
                    ,NEW_LAST_NAME 		
                    ,NEW_PRESONAL_ID 	
                    ,NEW_KIND_OF_SEX 	
                    ,NEW_BIRTH_DATE 	
                    ,NEW_MONEY 			
                    ,NEW_DEPARTMENT_CODE
            )
               VALUES
               (
                    SYSDATE
                    , 'INSERT'
                    , USER
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , :NEW.ID
                    , :NEW.FIRST_NAME 
                    , :NEW.LAST_NAME 
                    , :NEW.PRESONAL_ID
                    , :NEW.KIND_OF_SEX
                    , :NEW.BIRTH_DATE
                    , :NEW.MONEY
                    , :NEW.DEPARTMENT_CODE
               );
    ELSIF updating THEN
            INSERT INTO employees_archives
               ( 
                     EVENT_DATE			
                    ,EVENT_TYPE			
                    ,USER_NAME			
                    ,OLD_ID 			
                    ,OLD_FIRST_NAME 	
                    ,OLD_LAST_NAME 		
                    ,OLD_PRESONAL_ID 	
                    ,OLD_KIND_OF_SEX 	
                    ,OLD_BIRTH_DATE 	
                    ,OLD_MONEY 			
                    ,OLD_DEPARTMENT_CODE
                    ,NEW_ID 			
                    ,NEW_FIRST_NAME 	
                    ,NEW_LAST_NAME 		
                    ,NEW_PRESONAL_ID 	
                    ,NEW_KIND_OF_SEX 	
                    ,NEW_BIRTH_DATE 	
                    ,NEW_MONEY 			
                    ,NEW_DEPARTMENT_CODE
            )
               VALUES
               (
                    SYSDATE
                    , 'UPDATE'
                    , USER
                    , :OLD.ID
                    , :OLD.FIRST_NAME 
                    , :OLD.LAST_NAME 
                    , :OLD.PRESONAL_ID
                    , :OLD.KIND_OF_SEX
                    , :OLD.BIRTH_DATE
                    , :OLD.MONEY
                    , :OLD.DEPARTMENT_CODE
                    , :NEW.ID
                    , :NEW.FIRST_NAME 
                    , :NEW.LAST_NAME 
                    , :NEW.PRESONAL_ID
                    , :NEW.KIND_OF_SEX
                    , :NEW.BIRTH_DATE
                    , :NEW.MONEY
                    , :NEW.DEPARTMENT_CODE
               );
    ELSE 

                INSERT INTO employees_archives
               ( 
                     EVENT_DATE			
                    ,EVENT_TYPE			
                    ,USER_NAME			
                    ,OLD_ID 			
                    ,OLD_FIRST_NAME 	
                    ,OLD_LAST_NAME 		
                    ,OLD_PRESONAL_ID 	
                    ,OLD_KIND_OF_SEX 	
                    ,OLD_BIRTH_DATE 	
                    ,OLD_MONEY 			
                    ,OLD_DEPARTMENT_CODE
                    ,NEW_ID 			
                    ,NEW_FIRST_NAME 	
                    ,NEW_LAST_NAME 		
                    ,NEW_PRESONAL_ID 	
                    ,NEW_KIND_OF_SEX 	
                    ,NEW_BIRTH_DATE 	
                    ,NEW_MONEY 			
                    ,NEW_DEPARTMENT_CODE
            )
               VALUES
               (
                    SYSDATE
                    , 'DELETE'
                    , USER
                    , :OLD.ID
                    , :OLD.FIRST_NAME 
                    , :OLD.LAST_NAME 
                    , :OLD.PRESONAL_ID
                    , :OLD.KIND_OF_SEX
                    , :OLD.BIRTH_DATE
                    , :OLD.MONEY
                    , :OLD.DEPARTMENT_CODE
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
                    , NULL
               );

    END IF;
END;

/
ALTER TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUID_EMPLOYEES_ARCHIVES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES" 
AFTER INSERT OR UPDATE OR DELETE
ON employees
FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO employees_archives
   ( 
         EVENT_DATE			
        ,EVENT_TYPE			
        ,USER_NAME			
        ,OLD_ID 			
        ,OLD_FIRST_NAME 	
        ,OLD_LAST_NAME 		
        ,OLD_PRESONAL_ID 	
        ,OLD_KIND_OF_SEX 	
        ,OLD_BIRTH_DATE 	
        ,OLD_MONEY 			
        ,OLD_DEPARTMENT_CODE
        ,NEW_ID 			
        ,NEW_FIRST_NAME 	
        ,NEW_LAST_NAME 		
        ,NEW_PRESONAL_ID 	
        ,NEW_KIND_OF_SEX 	
        ,NEW_BIRTH_DATE 	
        ,NEW_MONEY 			
        ,NEW_DEPARTMENT_CODE
)
   VALUES
   (
        SYSDATE
        , 'INSERT'
        , USER
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , NULL
        , :NEW.ID
        , :NEW.FIRST_NAME 
        , :NEW.LAST_NAME 
        , :NEW.PRESONAL_ID
        , :NEW.KIND_OF_SEX
        , :NEW.BIRTH_DATE
        , :NEW.MONEY
        , :NEW.DEPARTMENT_CODE
   );
END;

/
ALTER TRIGGER "SHOP"."AUID_EMPLOYEES_ARCHIVES" ENABLE;
--------------------------------------------------------
--  Constraints for Table ABSENCJE
--------------------------------------------------------

  ALTER TABLE "SHOP"."ABSENCJE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "SHOP"."DEPARTMENTS" ADD CONSTRAINT "DEPARTMENTS_PK" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SHOP"."DEPARTMENTS" MODIFY ("MANAGER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS2
--------------------------------------------------------

  ALTER TABLE "SHOP"."DEPARTMENTS2" MODIFY ("MANAGER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "SHOP"."EMPLOYEES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."EMPLOYEES" ADD CHECK (kind_of_sex in ('M','K')) ENABLE;
  ALTER TABLE "SHOP"."EMPLOYEES" ADD CHECK (kind_of_sex in ('M','K')) ENABLE;
  ALTER TABLE "SHOP"."EMPLOYEES" MODIFY ("KIND_OF_SEX" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."EMPLOYEES" MODIFY ("PRESONAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."EMPLOYEES" ADD CONSTRAINT "EMPOLYEES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAKTURY_SPRZEDAZY
--------------------------------------------------------

  ALTER TABLE "SHOP"."FAKTURY_SPRZEDAZY" ADD PRIMARY KEY ("ID_FAKTURY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JEDNOSTKI_PRODUKTOW
--------------------------------------------------------

  ALTER TABLE "SHOP"."JEDNOSTKI_PRODUKTOW" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "SHOP"."KLIENCI" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."KLIENCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."KLIENCI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SHOP"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRZYCZYNY_ABSENCJI
--------------------------------------------------------

  ALTER TABLE "SHOP"."PRZYCZYNY_ABSENCJI" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."PRZYCZYNY_ABSENCJI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RODZAJE_SRODKOW_TRANSPORTU
--------------------------------------------------------

  ALTER TABLE "SHOP"."RODZAJE_SRODKOW_TRANSPORTU" MODIFY ("PELNA_NAZWA" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."RODZAJE_SRODKOW_TRANSPORTU" ADD PRIMARY KEY ("KOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "SHOP"."SUPPLIERS" MODIFY ("NAME_SUPPLIER" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."SUPPLIERS" ADD PRIMARY KEY ("ID_SUPPLIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPE_OF_PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SHOP"."TYPE_OF_PRODUCTS" MODIFY ("FULL_NAME_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "SHOP"."TYPE_OF_PRODUCTS" ADD CHECK (expiration_date in ('K', 'D')) ENABLE;
  ALTER TABLE "SHOP"."TYPE_OF_PRODUCTS" ADD PRIMARY KEY ("TYPE_OF_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAKUPY
--------------------------------------------------------

  ALTER TABLE "SHOP"."ZAKUPY" ADD PRIMARY KEY ("ID_ZAKUPU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAKUPY_POZYCJE
--------------------------------------------------------

  ALTER TABLE "SHOP"."ZAKUPY_POZYCJE" ADD PRIMARY KEY ("ID_ZAKUPU", "NUMER_POZYCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABSENCJE
--------------------------------------------------------

  ALTER TABLE "SHOP"."ABSENCJE" ADD FOREIGN KEY ("ID_PRACOWNIKA")
	  REFERENCES "SHOP"."EMPLOYEES" ("ID") ENABLE;
  ALTER TABLE "SHOP"."ABSENCJE" ADD FOREIGN KEY ("PA_KOD")
	  REFERENCES "SHOP"."PRZYCZYNY_ABSENCJI" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "SHOP"."DEPARTMENTS" ADD CONSTRAINT "FK_DEP_EMPLOYEE" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "SHOP"."EMPLOYEES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAKTURY_SPRZEDAZY
--------------------------------------------------------

  ALTER TABLE "SHOP"."FAKTURY_SPRZEDAZY" ADD FOREIGN KEY ("ID_KLIENTA")
	  REFERENCES "SHOP"."KLIENCI" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEDNOSTKI_PRODUKTOW
--------------------------------------------------------

  ALTER TABLE "SHOP"."JEDNOSTKI_PRODUKTOW" ADD FOREIGN KEY ("ID_PRODUKTU")
	  REFERENCES "SHOP"."PRODUCTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SHOP"."PRODUCTS" ADD CONSTRAINT "FK_TYPE_OF_PRODUCT" FOREIGN KEY ("TYPE_OF_PRODUCT")
	  REFERENCES "SHOP"."TYPE_OF_PRODUCTS" ("TYPE_OF_PRODUCT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "SHOP"."SUPPLIERS" ADD CONSTRAINT "FK_KOD_RODZAJ_SRODKOW_TRANSPORTU" FOREIGN KEY ("TYPE_CODE_TRANSPORT")
	  REFERENCES "SHOP"."RODZAJE_SRODKOW_TRANSPORTU" ("KOD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZAKUPY
--------------------------------------------------------

  ALTER TABLE "SHOP"."ZAKUPY" ADD FOREIGN KEY ("ID_KLIENTA")
	  REFERENCES "SHOP"."KLIENCI" ("ID") ENABLE;
  ALTER TABLE "SHOP"."ZAKUPY" ADD FOREIGN KEY ("ID_FAKTURY")
	  REFERENCES "SHOP"."FAKTURY_SPRZEDAZY" ("ID_FAKTURY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZAKUPY_POZYCJE
--------------------------------------------------------

  ALTER TABLE "SHOP"."ZAKUPY_POZYCJE" ADD FOREIGN KEY ("ID_ZAKUPU")
	  REFERENCES "SHOP"."ZAKUPY" ("ID_ZAKUPU") ENABLE;
  ALTER TABLE "SHOP"."ZAKUPY_POZYCJE" ADD FOREIGN KEY ("ID_PRODUKTU")
	  REFERENCES "SHOP"."PRODUCTS" ("ID") ENABLE;
